import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import CartBarPage from "./cartbar/page";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

// Define fonts
const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"], // Add weights as per your requirement
});

// Define metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className={poppins.className}>
        {children} {/* Render child components */}
        <Footer/>
        <CartBarPage />
      </body>
    </html>
  );
}
